### ISSUE TITLE
Not an issue but ...

### ISSUE THREAD

**Issue by merlinkv** [rcmolina/z802tzx3#1]
It's possible to add 4000bds speed?

I think will be very useful for many users.

Thanks in advance & kind regards

**Comment by rcmolina** [comment]
Hola @merlinkv, no me he puesto a revisar los parámtros porque creo que ya lo hice y estaba comentado a 4094, que era un múltiplo). Dime si te vale sí o necesitas que me ajuste a los 4000

**Comment by merlinkv** [comment]
Hola @rcmolina, 4000 estaría muy bien si pudiera ser.

Muchas gracias por anticipado y un saludo.

**Comment by rcmolina** [comment]
versión z80tzx4 con incrementos de 100 baudios desde 3500 a 4100

**Comment by merlinkv** [comment]
Hola @rcmolina.

¡Muchísimas gracias! Todos los juegos que no me iban a 4500 y tenía que hacerlos a 3500, ahora los puedo poner a 4100bds y funcionan perfectamente.
