### ISSUE TITLE
Contact!

### ISSUE THREAD

**Issue by fraespre** [rcmolina/z802tzx3#2]
Hola Rafa,

Estoy interesado en hacer una modificación sobre tu código de esta herramienta "z802tzx"
... pero no me termina de funcionar. Estoy seguro de que es una chorrada, pero no lo veo.
Podría contactar contigo para consultarte? Mi correo es fraespre@gmail.com

Ah! y perdona por crear esta incidencia. Por favor bórrala cuando leas el mensaje :-)

un saludo y gracias por adelantado,

**Comment by rcmolina** [comment]
Seguimos por correo en rcmolina@gmail.com
